node {
  def mvnHome

  stage('Preparation') {
    git branch: 'main', url: 'https://github.com/maplekiyo/java-demo.git'
    // Get the Maven tool.
    // ** Note: This 'M3' Maven tool must be configured
    // **       in the global configuration.
    mvnHome = tool 'M3'
  }

  stage('Build') {
    // Run the Maven build
    if (isUnix()) {
      sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
    } else {
      bat(/"${mvnHome}\bin\mvn' -Dmaven.test.failure.ignore clean package/)
    }
  }

  stage('Results') {
    junit '**/target/surefire-reports/TEST-*.xml'
    archive 'target/*.jar'
  }
}
